# Generated by Django 5.0.4 on 2024-04-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(blank=True),
        ),
    ]
