# Generated by Django 5.0.4 on 2024-04-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_todo_isdone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
    ]
