# Generated by Django 5.0.4 on 2024-04-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_isdone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['isDone']},
        ),
    ]
