# Generated by Django 5.0.4 on 2024-04-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={},
        ),
    ]
